### ISSUE TITLE
python3 parser.py -t generate_book_page_links

### ISSUE THREAD

**Issue by rosetta-andy** [starsdog/haodoo#1]
1.下載master.zip後解壓縮
2.執行第一個步驟'python3 parser.py -t generate_book_page_links'後發生以下錯誤:
Traceback (most recent call last):
  File "parser.py", line 197, in <module>
    project_config=json.load(file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 12 column 5 (char 682)

**Comment by chchwy** [comment]
看起來是 json 格式解析失敗，你有修改 `config.json` 嗎

**Comment by rosetta-andy** [comment]
謝謝你的答覆，在解壓縮master.zip後，我有看了一下config.json，但看起來不需要修改(抱歉，我不是很懂程式，我只能用看個大概)，接著我就執行'python3 parser.py -t generate_book_page_links'了

**Comment by chchwy** [comment]
因為錯誤訊息明寫著 json 解析失敗。json 是一種非常嚴格的格式，有時候人眼可讀，但是結尾多一個逗號，或者少一個引號都會直接導致整個檔案解析失敗。你可能要把 json 的內容貼上來才能幫你。

這裡有標明錯誤的地方，第十二行第五欄：
```
json.decoder.JSONDecodeError: Expecting value: line 12 column 5 (char 682)
```

ps. 個人不負責任猜測那裡多一個逗號。

**Comment by rosetta-andy** [comment]
謝謝解決小弟的疑問，小弟懂了，哈哈，見笑了，非常感謝。
